core/urls.py
from django.conf.urls import url, include
from registration.backends.simple.views import RegistrationView

from .views import HomeView, UserView, ProfileView, ProfileUpdateView, CommentView, CommentDetailView
from .forms import HoneyRegistrationForm

urlpatterns = [
    url(r'^user/$', UserView.as_view(), name='user'),
    url(r'^user/(?P<username>[\w-]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^user/(?P<username>[\w-]+)/edit/$', ProfileUpdateView.as_view(), name='profile_update'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^comment/(?P<pk>\d+)/$', CommentDetailView.as_view(), name='comment_detail'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search/$', HomeView.as_view(), name='search'),
    # Taken from registration.backends.simple.urls:
    url(r'^register/$',
        RegistrationView.as_view(form_class=HoneyRegistrationForm),
        name='registration_register'),
    url(r'^', include('registration.auth_urls')),
]

maps/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import (
    Map, New, Detail, Update,
    CityNew, CityUpdate, CityList,
    RatingView, RatingDetailView,
    BboxView, CitiesAutocompleteView, GeoJsonListView,
)

urlpatterns = [
    url(r'^place/new/$', login_required(New.as_view()), name='new'),
    url(r'^place/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', Detail.as_view(), name='detail'),
    url(r'^place/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit/$', login_required(Update.as_view()), name='update'),
    url(r'^rating/$', RatingView.as_view(), name='rating'),
    url(r'^rating/(?P<rating>\d\.\d)/$', RatingDetailView.as_view(), name='rating_detail'),
    url(r'^city/$', login_required(CityList.as_view()), name='cities'),
    url(r'^city/new/$', login_required(CityNew.as_view()), name='city_new'),
    url(r'^city/(?P<pk>[a-z-]+)/$', CityUpdate.as_view(), name='city'),
    url(r'^map/(?:(?P<city>[\w-]+)/)?$', Map.as_view(), name='map'),
    url(r'^api/geojson/(?:(?P<pk>\d+)/)?(?:(?P<city>[\w-]+)/)?$', GeoJsonListView.as_view(), name='geojson'),
    url(r'^api/bbox/(?:(?P<city>[\w-]+)/)?$', BboxView.as_view(), name='bbox'),
    url(r'^api/cities/$', CitiesAutocompleteView.as_view(), name='city_autocomplete')
]

core/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from django_countries.fields import CountryField


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    country = CountryField(verbose_name=_("country"), blank_label=_("Country"), blank=True)
    city = models.ForeignKey('maps.City', verbose_name=_("city"), related_name='profiles', null=True, blank=True)
    avatar = models.ImageField(_("avatar"), upload_to='avatars', blank=True)
    description = models.TextField(_("about me"), blank=True)
    why_i_joined = models.TextField(_("I joined ECOmaps because:"), blank=True)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

    def __str__(self):
        return self.user.get_full_name() or self.user.username

    def get_absolute_url(self):
        return reverse('profile', kwargs={'username': self.user.username})

maps/models.py
from geojson import Feature
import requests

from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.template import loader
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

from core.utils import round_half, star_to_list
from .fields import PointField
from .choices import CATEGORY_CHOICES, PRICE_CHOICES, get_cat
from .managers import TagManager, CityQuerySet, PlaceManager
TimeStampedModel = models.Model


class Tag(models.Model):
    name = models.CharField(_("name"), unique=True, max_length=42)
    slug = models.SlugField(_("slug"), unique=True)

    objects = TagManager()

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return self.name


class Rating(models.Model):
    place = models.ForeignKey('maps.Place')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    rating = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name = _("Rating")
        verbose_name_plural = _("Ratings")

    def __str__(self):
        return str(self.place.pk) + '*' * self.rating + self.user.username


class Place(TimeStampedModel):
    slug = models.SlugField()
    geom = PointField()
    name = models.CharField(verbose_name=_("name"), max_length=255)
    category = models.CharField(verbose_name=_("category"), max_length=25,
        choices=CATEGORY_CHOICES)
    tags = models.ManyToManyField('maps.Tag', verbose_name=_('tags'))
    description = models.TextField(_("description"), blank=True)
    price = models.PositiveSmallIntegerField(_("price"),
        choices=PRICE_CHOICES, default=0)
    city = models.ForeignKey('City', related_name='places')
    address = models.CharField(verbose_name=_("address"), max_length=255)
    locality = models.CharField(verbose_name=_("locality"), max_length=255)
    postcode = models.CharField(verbose_name=_("postcode"), max_length=12)
    phone_number = PhoneNumberField(verbose_name=_("phone number"), blank=True)
    email = models.EmailField(verbose_name=_("email"), blank=True)
    website = models.URLField(verbose_name=_("website"), blank=True)
    facebook = models.URLField(verbose_name=_("facebook"), blank=True)
    twitter = models.URLField(verbose_name=_("twitter"), blank=True)
    weloveit = models.CharField(verbose_name=_("why we love it"), blank=True,
        max_length=500, default="")
    picture = models.ImageField(_("picture"), upload_to='places', blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='places')
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modified')
    raters = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Rating', related_name="rated_places")

    objects = PlaceManager()

    class Meta:
        verbose_name = _("Place")
        verbose_name_plural = _("Places")

    def __str__(self):
        return self.name

    def price_symbol(self):
        symbol = "€"
        return " ".join(symbol * self.price)

    def phone(self):
        if not self.phone_number:
            return ''
        return self.phone_number.as_international

    @property
    def popupContent(self):
        template = loader.get_template('maps/popup.html')
        return template.render({'place': self})

    @property
    def feature(self):
        return Feature(
            geometry=self.geom,
            properties={
                'popupContent': self.popupContent,
                'color': get_cat(self.category).color}
        )

    @property
    def stars(self):
        avg = self.rating_set.aggregate(models.Avg('rating'))['rating__avg']
        return round_half(avg)

    @property
    def star_list(self):
        return star_to_list(self.stars)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id, 'slug': self.slug})


class City(TimeStampedModel):
    id = models.SlugField(primary_key=True, null=False, unique=True)
    name = models.CharField(verbose_name=_("name"), max_length=255)
    country = CountryField(verbose_name=_("country"), blank_label=_("Country"))
    bounds = JSONField(default=dict, blank=True)

    objects = CityQuerySet.as_manager()

    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")

    def __str__(self):
        return self.name

    def request_bounds(self):
        params = {
            'url': settings.OPENCAGE_URL,
            'key': settings.OPENCAGE_KEY,
            'query': self.id,
        }
        url = '{url}?q={query}&key={key}'.format(**params)
        response = requests.get(url)
        if response.ok:
            data = response.json()
            if data['total_results']:
                return data['results'][0]['bounds']
        return dict()

    def get_absolute_url(self):
        return reverse('city', kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        if not self.id:
            self.id = slugify(self.name)
        if not self.bounds:
            self.bounds = self.request_bounds()
        super().save(*args, **kwargs)

core/views.py
from collections import namedtuple
from random import choice
from os import path

from django.views import generic
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.staticfiles.templatetags.staticfiles import static

from django_comments.models import Comment

from maps.choices import CATEGORIES
from educational.models import Post, Topic
from .mixins import JsonResponseMixin
from .models import Profile
from .forms import HomeForm, ProfileForm, CommentForm


class CommentView(JsonResponseMixin, generic.CreateView):
    model = Comment
    form_class = CommentForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response(self.object)

    def form_invalid(self, form):
        return self.render_to_response(None)

    def get_data(self, comment):
        if comment:
            return {'url': reverse('comment_detail', kwargs={'pk': comment.pk})}
        return {'error': 'Invalid form'}


class CommentDetailView(generic.DetailView):
    model = Comment
    template_name = 'comment.html'


class HomeView(generic.FormView):
    form_class = HomeForm
    template_name = 'home.html'

    def background(self):
        bg_dir = settings.BACKGROUNDS_DIR
        backgrounds = [static(path.join(bg_dir, name)) for name in settings.BACKGROUNDS]
        return choice(backgrounds)

    def categories(self):
        return CATEGORIES

    def post_types(self):
        return Post.POST_TYPES_PLURAL

    def topics(self):
        return Topic.objects.all()


class UserView(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return reverse('profile', kwargs={'username': self.request.user})
        raise Http404


class ProfileView(generic.DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'core/profile_detail.html'

    def get_object(self):
        user = get_object_or_404(
            get_user_model(),
            username=self.kwargs['username'])
        DummyProfile = namedtuple('Profile', ['user', 'dummy'])
        dummy_profile = DummyProfile(user, True)
        return getattr(user, 'profile', dummy_profile)

    def places(self):
        return self.object.user.places.order_by('-id')[:4]


class ProfileUpdateView(UserPassesTestMixin, generic.UpdateView):
    model = Profile
    form_class = ProfileForm

    def test_func(self):
        return self.request.user.username == self.kwargs['username']

    def handle_no_permission(self):
        raise Http404

    def get_object(self):
        return Profile.objects.filter(user=self.request.user).first()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

maps/views.py
import geojson

from django.shortcuts import get_object_or_404

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.core.urlresolvers import reverse

from core.utils import qstr, round_half, star_to_list
from core.mixins import JsonResponseMixin
from .models import City, Place, Rating
from .forms import PlaceForm, CityForm, RatingForm
from .choices import CATEGORIES


class GeoJsonListView(JsonResponseMixin, generic.list.BaseListView):
    def get_queryset(self):
        if self.kwargs.get('pk'):
            places = [Place.objects.get(id=self.kwargs['pk'])]
        elif self.kwargs.get('city') in City.objects.ids():
            places = Place.objects.filter(city=self.kwargs.pop('city'))
        else:
            places = Place.objects.all()

        categories = dict(self.request.GET).get('cat')
        if categories:
            places = places.filter(category__in=categories)

        search = self.request.GET.get('q')
        if search:
            places = places.filter(
                Q(name__icontains=search)
                | Q(description__icontains=search)
                | Q(locality__icontains=search)
            )

        return places

    def get_data(self, context):
        return geojson.FeatureCollection(
            [obj.feature for obj in context['object_list']]
        )


class BboxView(JsonResponseMixin, generic.View):
    http_method_names = [u'get']

    def get(self, request, *args, **kwargs):
        return self.render_to_response(context=self.kwargs)

    def get_data(self, context):
        city = get_object_or_404(City, id=context.get('city'))
        return city.bounds


class CitiesAutocompleteView(JsonResponseMixin, generic.View):
    http_method_names = [u'get']

    def get(self, request, *args, **kwargs):
        return self.render_to_response(context=self.kwargs)

    def get_data(self, context):
        suggestions = [{'data': data, 'value': value}
            for data, value in City.objects.values_with_country()]
        return {
            'query': 'Unit',
            'suggestions': suggestions,
        }


class RatingView(LoginRequiredMixin, JsonResponseMixin, generic.CreateView):
    model = Rating
    form_class = RatingForm
    raise_exception = True

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response(self.object)

    def form_invalid(self, form):
        return self.render_to_response(form)

    def get_data(self, data):
        if isinstance(data, Rating):
            rating = data
            return {
                'rating': rating.rating,
                'stars': rating.place.stars,
                'url': reverse('rating_detail', kwargs={'rating': rating.place.stars}),
            }
        return {'error': data.errors}


class RatingDetailView(generic.TemplateView):
    template_name = 'maps/rating_detail.html'

    def get(self, request, *args, **kwargs):
        self.rating = round_half(float(kwargs['rating']))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stars'] = star_to_list(self.rating)
        return context

class Map(generic.TemplateView):
    template_name = 'map.html'

    def get(self, request, *args, **kwargs):
        """ Move city from query string to URL. """
        if 'city' in request.GET:
            query_string = dict(request.GET)
            self.city_id = query_string.pop('city')[0]
            if self.city_id:
                url = reverse('map', kwargs={'city': self.city_id}) + qstr(query_string)
            else:
                url = reverse('map') + qstr(query_string)
            return redirect(url)
        if 'city' in kwargs:
            self.city_id = kwargs.get('city')
        return super().get(request, *args, **kwargs)

    def city(self):
        return City.objects.get(id=self.city_id)

    def categories(self):
        return CATEGORIES


class New(generic.CreateView):
    model = Place
    form_class = PlaceForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        if self.request.GET.get('city'):
            kwargs['city'] = self.request.GET.get('city')
        return kwargs


class Update(generic.UpdateView):
    model = Place
    form_class = PlaceForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class Detail(generic.DetailView):
    template_name = 'maps/place_detail.html'
    model = Place

    def stars(self):
        return star_to_list(self.object.stars)


class CityNew(generic.CreateView):
    model = City
    form_class = CityForm


class CityList(generic.ListView):
    model = City
    ordering = 'country'


class CityUpdate(generic.UpdateView):
    model = City
    form_class = CityForm

core/templates/analytics.html
{% if debug or staging or request.DNT %}
  <!-- No Google Analytics -->
{% else %}
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41831357-2', 'auto');
    ga('send', 'pageview');
  </script>
{% endif %}

core/templates/auth_menu.html
{% load i18n %}
    <li><a href="{% url 'login' %}">{% trans "Log In" %}</a></li>
    <li><a href="{% url 'registration_register' %}">{% trans "Sign Up" %}</a></li>

core/templates/base.html
{% load static i18n %}{% load compress %}<!DOCTYPE html>
<html xml:lang="{{ LANGUAGE_CODE }}">
<head>
  <title>{% block page_title %}{% endblock %} | ECOmaps</title>
  {% if debug or staging %}
    <meta name="robots" content="noindex, nofollow">
  {% endif %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <link rel="icon" type="image/png" href="{% static "img/favicon-alpha.png" %}" />
  {% compress css %}
      <link type="text/css" rel="stylesheet" href="{% static "Materialize/dist/css/materialize.min.css" %}" media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static "select2/dist/css/select2.min.css" %}" media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static "leaflet/dist/leaflet.css" %}" media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static "leaflet-draw/dist/leaflet.draw.css" %}" media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static "css/material-icons.css" %}" media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static "css/maps.css" %}" media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="{% static "css/style.css" %}" media="screen,projection"/>
  {% endcompress %}
  {% block extra_css %}{% endblock %}
  {% block extra_head %}{% endblock %}
  {% include "analytics.html" %}
</head>

<body class="{% block body_class %}{% endblock %}">
  {% if debug %}<b class="site-state indigo center-align">DEBUG</b>{% endif %}
  {% if staging %}<b class="site-state purple center-align">TEST</b>{% endif %}

  {% block header %}
    {% include "header.html" %}
  {% endblock %}

  <section id="main">
    {% block main %}
      <article id="content" class="">
        {% block content %}You should add some content here! ;-){% endblock %}
      </article>
    {% endblock %}
  </section>

  {% include "footer.html" %}

  {% compress js %}
    <script type="text/javascript" src="{% static "jquery/dist/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "leaflet/dist/leaflet.js" %}"></script>
    <script type="text/javascript" src="{% static "leaflet-draw/dist/leaflet.draw.js" %}"></script>
    <script type="text/javascript" src="{% static "Materialize/dist/js/materialize.js" %}"></script>
    <script type="text/javascript" src="{% static "select2/dist/js/select2.js" %}"></script>
    <script type="text/javascript" src="{% static "urijs/src/URI.min.js" %}"></script>
    <script type="text/javascript" src="{% static "devbridge-autocomplete/dist/jquery.autocomplete.js" %}"></script>
    <script type="text/javascript" src="{% static "js/ui.js" %}"></script>
    <script type="text/javascript" src="{% static "js/maps.js" %}"></script>
    <script type="text/javascript" src="{% static "js/comments.js" %}"></script>
    <script type="text/javascript" src="{% static "js/rating.js" %}"></script>
    <script type="text/javascript" src="{% static "js/csrf.js" %}"></script>
  {% endcompress %}


  {% block extra_js %}{% endblock %}
</body>
</html>

core/templates/comment.html
{% load humanize %}

<li class="comment collection-item avatar" id="c{{ comment.id }}">
    {% if comment.user.profile.avatar %}
        <img class="circle" src="{{ comment.user.profile.avatar.url }}" alt="" />
    {% else %}
        <i class="material-icons circle" style="font-size: 2rem">face</i>
    {% endif %}
    <div class="title">
        {{ comment.comment|linebreaks }}
    </div>
    <p class="">
        <a href="{% url 'profile' comment.user %}">
            {% firstof comment.user.first_name comment.user.username %}
        </a>
        <span class="sep grey-text">⦁</span>
        <span class="datetime grey-text" title="{{ comment.submit_date|date:"D d M Y" }} {{ comment.submit_date|time:"H:i" }}" style="cursor:help">
            {{ comment.submit_date|naturaltime }}
        </span>
    </p>
</li>

core/templates/comments.html
{% load comments %}
{% load i18n %}

{% get_comment_list for object as comment_list %}

<ul id="comments" class="collection">
    {% if user.is_authenticated %}
        <li class="comment collection-item avatar" id="new-comment">
            {% if user.profile.avatar %}
                <img class="circle" src="{{ user.profile.avatar.url }}" alt="" />
            {% else %}
                <i class="material-icons circle" style="font-size: 2rem">face</i>
            {% endif %}
            <form id="comment-form" action="{% url 'comment' %}" method="post">
                {% csrf_token %}
                <input class="mielpoto" id="id_name" type="text" name="name" value=""
                       placeholder="{% trans "I guess thou shouldn’t fill this" %}">
                <textarea id="id_comment" class="materialize-textarea" name="comment" length="500"
                          placeholder="{% trans "Express yourself!" %}"></textarea>
            <button type="submit" for="comment-form" class="secondary-content btn-floating waves-effect waves-light blue-grey darken-1" href="#">
                <i class="material-icons">send</i>
            </button>
            </form>
        </li>
    {% else %}
        <li class="comment collection-item avatar" id="new-comment">
            <i class="material-icons circle" style="font-size: 2rem">face</i>
            <input type="text" disabled value="{% trans "You need to login to comment" %}">
            <a class="secondary-content btn blue-grey darken-1"
               href="{% url 'login' %}?next={{ request.get_full_path }}#comments">
                {% trans "Log in" %}
            </a>
        </li>
    {% endif %}
    {% for comment in comment_list reversed %}
        {% include "comment.html" %}
    {% endfor %}
</ul>

core/templates/footer.html
{% load static i18n %}
    <footer class="row">
        <ul id="partners" class="col offset-m1 m10">
            <li>
                <a href="http://www.iynf.org/" target="_blank">
                    <img id="IYNF" class="partner-logo" src="{% static 'img/partner/IYNF.png' %}" alt="IYNF" />
                </a>
            </li>
            <li>
                <a href="https://europa.eu/eyd2015/" target="_blank">
                    <img id="EYD" class="partner-logo" src="{% static 'img/partner/EYD.png' %}" alt="European year for development" />
                </a>
            </li>
            <li>
                <a href="http://www.concordeurope.org/" target="_blank">
                    <img id="Concord" class="partner-logo" src="{% static 'img/partner/Concord.png' %}" alt="Concord" />
                </a>
            </li>
            <li>
                <a href="https://europa.eu/eyd2015/en/csa" target="_blank">
                    <img id="CSA" class="partner-logo" src="{% static 'img/partner/CSA.png' %}" alt="CSA" />
                </a>
            </li>
        </ul>

        <div class="col offset-m1 m10">
            <div class="row">
              <div class="col s12 m6">
                <ul id="footer-links" class="row">
                    <li class="col s12 l4">
                        <a class="legal" href="{% trans '/about/' %}">{% trans "About" %}</a>
                    </li>
                    <li class="col s12 l4">
                        <a class="legal" href="/terms/">{% trans "Term of service" %}</a>
                    </li>
                    <li class="col s12 l4">
                        <a class="legal" href="/privacy/">{% trans "Privacy policy" %}</a>
                    </li>
                </ul>
              </div>
              <div class="col s12 m6 right-align">
                  <a href="https://facebook.com/green.ecomaps" target="_blank">
                      <img src="{% static "img/Icon_facebook.png" %}" alt="facebook" />
                  </a>
                  {% comment %}
                  <a href="https://instagram.com/explore/tags/ecomap/" target="_blank">
                      <img src="{% static "img/Icon_Instagram.png" %}" alt="Instagram" />
                  </a>
                  <a href="https://twitter.com/search?q=ecomaps%20iynf" target="_blank">
                      <img src="{% static "img/Icon_twitter.png" %}" alt="twitter" />
                  </a>
                  {% endcomment %}
                  <a href="mailto:henrique@iynf.org" target="_blank">
                      <img src="{% static "img/Icon_email.png" %}" alt="email" />
                  </a>
              </div>
            </div>
        </div>
    </footer>

core/templates/header.html
{% load static i18n %}
  <header>
    <nav id="main-menu">
      <div class="nav-wrapper container">

        <a href="{% url 'home' %}" class="brand-logo">
          <img src="{% static 'img/ecomaps.png' %}"
               alt="Ecomaps"
               title="{% trans "Back to Home" %}" />
        </a>

        <a href="#" data-activates="mobile-menu" class="button-collapse">
          <i class="mdi-navigation-menu"></i>
        </a>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
            <li>
                <a href="#" data-activates="user-menu" class='dropdown-button'>
                    {% blocktrans with name=user.username trimmed %}
                        Hello {{ name }}!
                    {% endblocktrans %}
                </a>
            </li>
          {% else %}
            {% include "auth_menu.html" %}
          {% endif %}
        </ul>
        <ul id="mobile-menu" class="side-nav">
          {% include "mobile_menu.html" %}
        </ul>
        <ul id="user-menu" class="dropdown-content">
            {% include "user_menu.html" %}
        </ul>

        {% if city %}
            {% url 'map' city=city as action %}
        {% else %}
            {% url 'map' as action %}
        {% endif %}
        <form class="right search hide-on-med-and-down" method="get"
             action="{{ action }}">
          <div class="input-field col s3">
            <input id="search" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search in {{ view.city.name }}...">
            <label for="search"><i class="material-icons">search</i></label>
          </div>
        </form>
      </div>
    </nav>



    <div id="submenu" class="nav-wrapper">
        <ul class="container">
            {% include "maps/filters.html" %}
            {% include "submenu.html" %}
        </ul>
    </div>
  </header>

core/templates/login_header.html
{% load static %}
<header class="container center-align">
    <div class="row"> </div>
    <img src="{% static "img/ecomaps-medium.png" %}" alt="ECOmaps" />
</header>

core/templates/map.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% if city %}
        {% blocktrans with city=view.city.name %}Map of {{ city }}{% endblocktrans %}
    {% else %}
        {% trans "Map" %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <div id="geojson-url" class="hide">{% url 'geojson' city=city %}?{{ request.GET.urlencode }}</div>
        <div id="geojson-bbox-url" class="hide">{% url 'bbox' city=city %}</div>
        <div id="no-place-found" class="hide">{% trans "Sorry, no place found." %}</div>
        <div id="map" class="map"></div>
    </div>
{% endblock content %}

core/templates/mobile_menu.html
{% load i18n %}
{% if user.is_authenticated %}
    {% include "user_menu.html" %}
{% else %}
    {% include "auth_menu.html" %}
{% endif %}
{% include "submenu.html" %}

core/templates/user_menu.html
{% load i18n %}
    <li><a href="{% url 'profile' user %}">{% trans "Profile" %}</a></li>
    <li><a href="{% url 'logout' %}?next=/">{% trans "Log out" %}</a></li>