core/urls.py
from django.conf.urls import url, include
from registration.backends.simple.views import RegistrationView

from .views import HomeView, UserView, ProfileView, ProfileUpdateView, CommentView, CommentDetailView
from .forms import HoneyRegistrationForm

urlpatterns = [
    url(r'^user/$', UserView.as_view(), name='user'),
    url(r'^user/(?P<username>[\w-]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^user/(?P<username>[\w-]+)/edit/$', ProfileUpdateView.as_view(), name='profile_update'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^comment/(?P<pk>\d+)/$', CommentDetailView.as_view(), name='comment_detail'),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search/$', HomeView.as_view(), name='search'),
    # Taken from registration.backends.simple.urls:
    url(r'^register/$',
        RegistrationView.as_view(form_class=HoneyRegistrationForm),
        name='registration_register'),
    url(r'^', include('registration.auth_urls')),
]

maps/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import (
    Map, New, Detail, Update,
    CityNew, CityUpdate, CityList,
    RatingView, RatingDetailView,
    BboxView, CitiesAutocompleteView, GeoJsonListView,
)

urlpatterns = [
    url(r'^place/new/$', login_required(New.as_view()), name='new'),
    url(r'^place/(?P<pk>\d+)/(?P<slug>[\w-]+)/$', Detail.as_view(), name='detail'),
    url(r'^place/(?P<pk>\d+)/(?P<slug>[\w-]+)/edit/$', login_required(Update.as_view()), name='update'),
    url(r'^rating/$', RatingView.as_view(), name='rating'),
    url(r'^rating/(?P<rating>\d\.\d)/$', RatingDetailView.as_view(), name='rating_detail'),
    url(r'^city/$', login_required(CityList.as_view()), name='cities'),
    url(r'^city/new/$', login_required(CityNew.as_view()), name='city_new'),
    url(r'^city/(?P<pk>[a-z-]+)/$', CityUpdate.as_view(), name='city'),
    url(r'^map/(?:(?P<city>[\w-]+)/)?$', Map.as_view(), name='map'),
    url(r'^api/geojson/(?:(?P<pk>\d+)/)?(?:(?P<city>[\w-]+)/)?$', GeoJsonListView.as_view(), name='geojson'),
    url(r'^api/bbox/(?:(?P<city>[\w-]+)/)?$', BboxView.as_view(), name='bbox'),
    url(r'^api/cities/$', CitiesAutocompleteView.as_view(), name='city_autocomplete')
]

maps/models.py
from geojson import Feature
import requests

from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.template import loader
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

from core.utils import round_half, star_to_list
from .fields import PointField
from .choices import CATEGORY_CHOICES, PRICE_CHOICES, get_cat
from .managers import TagManager, CityQuerySet, PlaceManager
TimeStampedModel = models.Model


class Tag(models.Model):
    name = models.CharField(_("name"), unique=True, max_length=42)
    slug = models.SlugField(_("slug"), unique=True)

    objects = TagManager()

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    def __str__(self):
        return self.name


class Rating(models.Model):
    place = models.ForeignKey('maps.Place')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    rating = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name = _("Rating")
        verbose_name_plural = _("Ratings")

    def __str__(self):
        return str(self.place.pk) + '*' * self.rating + self.user.username


class Place(TimeStampedModel):
    slug = models.SlugField()
    geom = PointField()
    name = models.CharField(verbose_name=_("name"), max_length=255)
    category = models.CharField(verbose_name=_("category"), max_length=25,
        choices=CATEGORY_CHOICES)
    tags = models.ManyToManyField('maps.Tag', verbose_name=_('tags'))
    description = models.TextField(_("description"), blank=True)
    price = models.PositiveSmallIntegerField(_("price"),
        choices=PRICE_CHOICES, default=0)
    city = models.ForeignKey('City', related_name='places')
    address = models.CharField(verbose_name=_("address"), max_length=255)
    locality = models.CharField(verbose_name=_("locality"), max_length=255)
    postcode = models.CharField(verbose_name=_("postcode"), max_length=12)
    phone_number = PhoneNumberField(verbose_name=_("phone number"), blank=True)
    email = models.EmailField(verbose_name=_("email"), blank=True)
    website = models.URLField(verbose_name=_("website"), blank=True)
    facebook = models.URLField(verbose_name=_("facebook"), blank=True)
    twitter = models.URLField(verbose_name=_("twitter"), blank=True)
    weloveit = models.CharField(verbose_name=_("why we love it"), blank=True,
        max_length=500, default="")
    picture = models.ImageField(_("picture"), upload_to='places', blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='places')
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modified')
    raters = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Rating', related_name="rated_places")

    objects = PlaceManager()

    class Meta:
        verbose_name = _("Place")
        verbose_name_plural = _("Places")

    def __str__(self):
        return self.name

    def price_symbol(self):
        symbol = "€"
        return " ".join(symbol * self.price)

    def phone(self):
        if not self.phone_number:
            return ''
        return self.phone_number.as_international

    @property
    def popupContent(self):
        template = loader.get_template('maps/popup.html')
        return template.render({'place': self})

    @property
    def feature(self):
        return Feature(
            geometry=self.geom,
            properties={
                'popupContent': self.popupContent,
                'color': get_cat(self.category).color}
        )

    @property
    def stars(self):
        avg = self.rating_set.aggregate(models.Avg('rating'))['rating__avg']
        return round_half(avg)

    @property
    def star_list(self):
        return star_to_list(self.stars)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.id, 'slug': self.slug})


class City(TimeStampedModel):
    id = models.SlugField(primary_key=True, null=False, unique=True)
    name = models.CharField(verbose_name=_("name"), max_length=255)
    country = CountryField(verbose_name=_("country"), blank_label=_("Country"))
    bounds = JSONField(default=dict, blank=True)

    objects = CityQuerySet.as_manager()

    class Meta:
        verbose_name = _("City")
        verbose_name_plural = _("Cities")

    def __str__(self):
        return self.name

    def request_bounds(self):
        params = {
            'url': settings.OPENCAGE_URL,
            'key': settings.OPENCAGE_KEY,
            'query': self.id,
        }
        url = '{url}?q={query}&key={key}'.format(**params)
        response = requests.get(url)
        if response.ok:
            data = response.json()
            if data['total_results']:
                return data['results'][0]['bounds']
        return dict()

    def get_absolute_url(self):
        return reverse('city', kwargs={'pk': self.id})

    def save(self, *args, **kwargs):
        if not self.id:
            self.id = slugify(self.name)
        if not self.bounds:
            self.bounds = self.request_bounds()
        super().save(*args, **kwargs)

maps/forms.py
from geojson import Point

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify

from .models import City, Place, Tag, Rating
from .form_fields import TagField


class RatingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    class Meta:
        model = Rating
        fields = ('place', 'rating')

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if rating not in range(1, 6):
            raise forms.ValidationError("Out of rating range.")
        return rating

    def save(self):
        rating, created = Rating.objects.update_or_create(
            place=self.cleaned_data['place'],
            user=self.request.user,
            defaults={'rating': self.cleaned_data['rating']})
        return rating


class CityForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['country'].widget.attrs['class'] = ' browser-default'

    class Meta:
        model = City
        fields = ('name', 'country')


class PlaceForm(forms.ModelForm):
    lat = forms.FloatField(label=_("Latitude"))
    lng = forms.FloatField(label=_("Longitude"))
    tags = TagField(queryset=Tag.objects.used(), required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.new = bool(kwargs['instance'])
        city = kwargs.pop('city', None)
        super().__init__(*args, **kwargs)
        if city:
            self.initial['city'] = city
        if self.instance.geom:
            coord = self.instance.geom['coordinates']
            self.initial['lng'], self.initial['lat'] = coord[0], coord[1]
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'validate'
            if field.widget.__class__.__name__ == 'Textarea':
                field.widget.attrs['class'] += ' materialize-textarea'
            if name == 'category':
                field.widget.attrs['class'] += ' browser-default'
            if field.required:
                field.widget.attrs['required'] = True
        for name, errors in self.errors.items():
            self.fields[name].widget.attrs['class'] += ' invalid card-panel'

    class Meta:
        model = Place
        fields = (
            'name',
            'city',
            'category',
            'price',
            'description',
            'weloveit',
            'picture',
            'tags',
            'website',
            'facebook',
            'twitter',
            'email',
            'phone_number',
            'address',
            'locality',
            'postcode',
            'lat',
            'lng',
        )

    def save(self, commit=True):
        place = super().save(commit=False)
        if not self.new:
            place.created_by = self.user
        place.modified_by = self.user
        lat = self.cleaned_data['lat']
        lng = self.cleaned_data['lng']
        place.geom = Point([lng, lat])
        place.slug = slugify(self.cleaned_data['name'])
        if commit:
            place.save()
            self.save_m2m()
        return place

maps/views.py
import geojson

from django.shortcuts import get_object_or_404

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.core.urlresolvers import reverse

from core.utils import qstr, round_half, star_to_list
from core.mixins import JsonResponseMixin
from .models import City, Place, Rating
from .forms import PlaceForm, CityForm, RatingForm
from .choices import CATEGORIES


class GeoJsonListView(JsonResponseMixin, generic.list.BaseListView):
    def get_queryset(self):
        if self.kwargs.get('pk'):
            places = [Place.objects.get(id=self.kwargs['pk'])]
        elif self.kwargs.get('city') in City.objects.ids():
            places = Place.objects.filter(city=self.kwargs.pop('city'))
        else:
            places = Place.objects.all()

        categories = dict(self.request.GET).get('cat')
        if categories:
            places = places.filter(category__in=categories)

        search = self.request.GET.get('q')
        if search:
            places = places.filter(
                Q(name__icontains=search)
                | Q(description__icontains=search)
                | Q(locality__icontains=search)
            )

        return places

    def get_data(self, context):
        return geojson.FeatureCollection(
            [obj.feature for obj in context['object_list']]
        )


class BboxView(JsonResponseMixin, generic.View):
    http_method_names = [u'get']

    def get(self, request, *args, **kwargs):
        return self.render_to_response(context=self.kwargs)

    def get_data(self, context):
        city = get_object_or_404(City, id=context.get('city'))
        return city.bounds


class CitiesAutocompleteView(JsonResponseMixin, generic.View):
    http_method_names = [u'get']

    def get(self, request, *args, **kwargs):
        return self.render_to_response(context=self.kwargs)

    def get_data(self, context):
        suggestions = [{'data': data, 'value': value}
            for data, value in City.objects.values_with_country()]
        return {
            'query': 'Unit',
            'suggestions': suggestions,
        }


class RatingView(LoginRequiredMixin, JsonResponseMixin, generic.CreateView):
    model = Rating
    form_class = RatingForm
    raise_exception = True

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return self.render_to_response(self.object)

    def form_invalid(self, form):
        return self.render_to_response(form)

    def get_data(self, data):
        if isinstance(data, Rating):
            rating = data
            return {
                'rating': rating.rating,
                'stars': rating.place.stars,
                'url': reverse('rating_detail', kwargs={'rating': rating.place.stars}),
            }
        return {'error': data.errors}


class RatingDetailView(generic.TemplateView):
    template_name = 'maps/rating_detail.html'

    def get(self, request, *args, **kwargs):
        self.rating = round_half(float(kwargs['rating']))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stars'] = star_to_list(self.rating)
        return context

class Map(generic.TemplateView):
    template_name = 'map.html'

    def get(self, request, *args, **kwargs):
        """ Move city from query string to URL. """
        if 'city' in request.GET:
            query_string = dict(request.GET)
            self.city_id = query_string.pop('city')[0]
            if self.city_id:
                url = reverse('map', kwargs={'city': self.city_id}) + qstr(query_string)
            else:
                url = reverse('map') + qstr(query_string)
            return redirect(url)
        if 'city' in kwargs:
            self.city_id = kwargs.get('city')
        return super().get(request, *args, **kwargs)

    def city(self):
        return City.objects.get(id=self.city_id)

    def categories(self):
        return CATEGORIES


class New(generic.CreateView):
    model = Place
    form_class = PlaceForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        if self.request.GET.get('city'):
            kwargs['city'] = self.request.GET.get('city')
        return kwargs


class Update(generic.UpdateView):
    model = Place
    form_class = PlaceForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class Detail(generic.DetailView):
    template_name = 'maps/place_detail.html'
    model = Place

    def stars(self):
        return star_to_list(self.object.stars)


class CityNew(generic.CreateView):
    model = City
    form_class = CityForm


class CityList(generic.ListView):
    model = City
    ordering = 'country'


class CityUpdate(generic.UpdateView):
    model = City
    form_class = CityForm

maps/templates/maps/city_form.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}
    {% if city %}
        {{ city.name }}
    {% else %}
        {% trans "New city" %}
    {% endif %}
{% endblock %}

{% block content %}
    <h2 class="center-align">
        {% if city %}
            {{ city.name }}
        {% else %}
            {% trans "New city" %}
        {% endif %}
    </h2>


    <form class="container" action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}

        <div class="row">
          <p class="input-field">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name.errors }}
            {{ form.name }}
          </p>
        </div>

        <div class="row">
          <p class="input-field">
            {{ form.country.errors }}
            {{ form.country }}
          </p>
        </div>

      <div class="row">
          {% if city %}
            <a href="{% url 'map' city.id %}" class="btn waves-effect left">
                {% trans "View on map" %}
            </a>
        {% endif %}

          <button class="btn waves-effect right" type="submit" name="action">
              {% if city %}
                {% trans "Update" %}
              {% else %}
                {% trans "Create" %}
              {% endif %}
          </button>
      </div>
    </form>
{% endblock content %}

maps/templates/maps/city_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Cities" %}{% endblock %}

{% block content %}
    <div class="container">

        <h2 class="center-align">{% trans "Cities" %}</h2>

        <div class="row">
            <a href="{% url 'city_new' %}"
               class="btn waves-effect blue-grey darken-3">
               {% trans "Add a new city" %}
            </a>
        </div>

        {% regroup city_list by country as country_list %}
        {% for country in country_list %}
            <ul class="collection with-header row">
                <li class="collection-header"><h5>{{ country.grouper.name }}</h5></li>
                {% for city in country.list %}
                    <li class="collection-item">
                        <a href="{% url 'map' city.id %}">
                            {{ city.name }}
                        </a>
                        <span class="grey-text">{{ city.places.count }}</span>
                        <span class="secondary-content" title="{% trans "Edit" %}"><a href="{% url 'city' city.id %}"><i class="material-icons">edit</i></a></span>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}

        <div class="row">
            <a href="{% url 'city_new' %}"
               class="btn waves-effect blue-grey darken-3">
               {% trans "Add a new city" %}
            </a>
        </div>
    </div>
{% endblock content %}

maps/templates/maps/filters.html
{% load i18n %}
{% if view.template_name == 'map.html' %}
    <li id="filters" class="right">
        <a id="filters-toggle" href="#" class="caret-down-after active">
            {% trans "Filters" %}
        </a>

        <ul id='filters-dropdown' class=''>
            {% for category in view.categories %}
              <li class="category{% if category.slug in request.GET.urlencode %} active{% endif %}">
                  <a href="#" id="{{ category.slug }}" class="category-link">
                      <img src="{{ category.icon }}" alt="icon-{{ category.slug }}" class="category-icon" />
                      <span class="category-name">
                          {{ category.name|upper }}
                      </span>
                  </a>
                  <ul class="subcategory-list">
                      {% for subcategory in category.subcategories %}
                          <li class="subcategory{% if subcategory.slug in request.GET.urlencode %} active{% endif %}">
                              <a href="#" id="{{ subcategory.slug }}" class="subcategory-link">
                                  <span class="subcategory-name">
                                      {{ subcategory.name }}
                                  </span>
                              </a>
                          </li>
                      {% endfor %}
                  </ul>
              </li>
            {% endfor %}
        </ul>
    </li>
{% endif %}

maps/templates/maps/place_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block page_title %}{{ place.name }}{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="center-align">{{ place.name }}</h2>

      <div class="row">
        <div class="col s12 l6">
          {% if place.picture %}
            <img src="{{ place.picture.url }}" alt="{{ place.picture.name }}" class="responsive-img place-picture z-depth-2" />
          {% else %}
            <a class="grey-text" href="{% url 'update' place.id place.slug %}#id_picture">
                <p class="center no-picture flow-text grey lighten-4">
                    {% trans "Add a picture to this place!" %}
                </p>
            </a>
          {% endif %}
        </div>

        {% autoescape off %}
            <div class="col s12 l6 flow-text">
                {{ place.description|linebreaks }}
            </div>
        {% endautoescape %}

      </div>
      <div class="row">
        <div class="col s12 m6">
          <div class="card deep-orange darken-4">
            <div class="card-content white-text">
              <div class="chip right help" title="{{ place.get_price_display }}">
                  <span id="price">{{ place.price_symbol }}</span>
              </div>
              <span class="card-title">{% blocktrans with category=place.get_category_display city=place.city.name trimmed %}
                  {{ category }} in {{ city }}
              {% endblocktrans %}</span>

              {% include "maps/rating.html" with stars=view.stars %}

              <h5>{% trans "Why we love it?" %}</h5>
              <p id="weloveit">{{ place.weloveit }}</p>
            </div>
            <div class="card-action">
                {% for tag in place.tags.all %}
                    <div class="chip">
                        {{ tag }}
                    </div>
                {% endfor %}
            </div>
          </div>
        </div>
        <div class="col s12 m6">
          <div class="card blue-grey darken-3">
            <div class="card-content white-text">
              <span class="card-title">{% trans "Contact" %}</span>
              <p class="right">{{ place.phone }}</p>
              <p>{{ place.address }}</p>
              <p>{{ place.locality }}</p>
              <p>{{ place.city.country }} – {{ place.postcode }}</p>
            </div>
            <div class="card-action">
                {% if place.email %}
                    <a href="mailto:{{ place.email }}">Email</a>
                {% endif %}
                {% if place.twitter %}
                    <a href="{{ place.twitter }}">Twitter</a>
                {% endif %}
                {% if place.website %}
                    <a href="{{ place.website }}">Website</a>
                {% endif %}
                {% if place.facebook %}
                    <a href="{{ place.facebook }}">facebook</a>
                {% endif %}
            </div>
          </div>
        </div>
      </div>

      <div id="geojson-url" class="hide">{% url 'geojson' pk=place.pk %}</div>
      <div id="map" class="row mini map"> </div>

      {% include "comments.html" %}

      <div class="row">
          <a href="{% url 'map' city=place.city.id %}"
             class="btn waves-effect left blue-grey darken-3">
             {% blocktrans with city=place.city.name trimmed %}
                 Back to {{ city }} map
             {% endblocktrans %}
          </a>

          {% if user.is_authenticated %}
            <a href="{% url 'update' place.id place.slug %}"
               class="btn waves-effect right blue-grey darken-3">
                  {% trans "Edit" %}
            </a>
          {% endif %}
      </div>
    </div>
{% endblock content %}

maps/templates/maps/popup.html
<div class="picture">
    {% if place.picture %}
        <img class="popup-place-picture" src="{{ place.picture.url }}" alt="" />
    {% endif %}
</div>
<div class="container">
    <h5>
        <a class="grey-text text-darken-4" href="{% url 'detail' pk=place.pk slug=place.slug %}">
            {{ place.name }}
        </a>
    </h5>
    
    <h6>{{ place.get_category_display }}</h6>
    
    <p>
        {% include "maps/rating.html" with place=place stars=place.star_list %}
    </p>
    
    <p>
        {{ place.description|truncatewords:30 }}
            <br>
        <span class="grey-text">
            <b style="float:right;cursor:help" title="{{ place.get_price_display}}">
                {{ place.price_symbol }}
            </b>
            <em>{{ place.tags.all|join:", " }}</em>
        </span>
    </p>
</div>

maps/templates/maps/rating.html
{% load static i18n %}
<form id="rating-form" class="" action="{% url 'rating' %}" method="post">
    <input type="hidden" id="id_place" name="place" value="{{ place.pk }}">
    <aside id="stars" class="">
        {% include "maps/rating_detail.html" %}
    </aside>
</form>

maps/templates/maps/rating_detail.html
{% load static i18n %}
<span class="rating-label">{% trans "Rate this place:" %}</span>
{% for star in stars %}
    <a href="#" class="rating-star" data-rating="{{ forloop.counter }}" title="{{ forloop.counter }}">
        {% if star == 'full' %}
            <img src="{% static "img/rating/star.png" %}" alt="{{ forloop.counter }} ({% trans "full star" %})" />
        {% endif %}
        {% if star == 'half' %}
            <img src="{% static "img/rating/halfstar.png" %}" alt="{{ forloop.counter }} ({% trans "half star" %})" />
        {% endif %}
        {% if star == 'empty' %}
            <img src="{% static "img/rating/nostar.png" %}" alt="{{ forloop.counter }} ({% trans "no star" %})" />
        {% endif %}
    </a>
{% endfor %}